version: "3.8"

services:
  falcon:
    build: .
    container_name: falcon-livecode
    restart: always

    ports:
      - "8010:8010"

    environment:
      PYTHONUNBUFFERED: "1"
      DOCKER_HOST: unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/falcon-workspace:/workspace

  python-runtime:
    image: fossunited/falcon-python:3.9

  golang-runtime:
    image: fossunited/falcon-golang

  rust-runtime:
    image: fossunited/falcon-rust

  js-runtime:
    image: frappedevs/falcon-javascript